### ISSUE TITLE
solo v2

### ISSUE THREAD

**Issue by 06kellyjac** [smlx/piv-agent#115]
Hello :wave: 

Has your solo v2 arrived yet?
If not I have mine so I'm happy to help with testing and maybe some development

**Comment by smlx** [comment]
Hi, thanks for checking in on this. My Solo v2 has arrived, but PIV support in the firmware has not. See https://github.com/solokeys/solo2/discussions/88 and also the existing issue https://github.com/smlx/piv-agent/issues/83.
